### ISSUE TITLE
I have one more issue I cant zoom in it just turns grey.

### ISSUE THREAD

**Issue by Mruble** [juliandescottes/piskel-website#14]

**Comment by juliandescottes** [comment]
I guess you are using a Chromebook & Chrome 57? See the following issue: https://github.com/juliandescottes/piskel/issues/651 

If you can take the time to comment on the issue and mention which chromebook model you own that would be nice.

I don't have any chromebook and the issue seems to only occur on this hardware. It also seems to be fixed with Chrome 58, according to @lokothodida .
Unless someone has the hardware and can spend some time investigating, I won't be able to work on this. The best would be to use Chrome 58 for now. I think you can change the release channel for Chrome even on chromebooks?

The "piskel-website" project is really dedicated to issues with the user pages, the home page etc..., any issue related to the editor itself should go to https://github.com/juliandescottes/piskel
-> https://github.com/juliandescottes/piskel/issues/new
There's also a detailed template when you file issues with the link above, which explains all the info needed to investigate efficiently :)

**Comment by juliandescottes** [comment]
I'm closing this issue since there is a duplicate one already created on the piskel repository, but we definitely should continue the conversation there!
